cmake_minimum_required(VERSION 3.22)
if(NOT DEFINED GAME_EXECUTABLE OR NOT DEFINED OUTPUT_DIRECTORY)
    message(FATAL_ERROR "Missing world summary test paths")
endif()
file(MAKE_DIRECTORY "${OUTPUT_DIRECTORY}")
function(run_summary name)
    execute_process(COMMAND "${GAME_EXECUTABLE}" --world-summary ${ARGN}
        WORKING_DIRECTORY "${OUTPUT_DIRECTORY}" TIMEOUT 90
        RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
    file(WRITE "${OUTPUT_DIRECTORY}/${name}.yaml" "${output}")
    file(WRITE "${OUTPUT_DIRECTORY}/${name}.stderr.log" "${error}")
    if(NOT "${result}" STREQUAL "0" OR NOT "${error}" STREQUAL "")
        message(FATAL_ERROR "World summary ${name} failed: ${result}\n${error}")
    endif()
    if(NOT output MATCHES "chunks: 441" OR NOT output MATCHES "final_digest: fnv1a64:")
        message(FATAL_ERROR "Incomplete world summary ${name}")
    endif()
    if(output MATCHES "OpenGL vendor:|\\[runtime\\] ready;")
        message(FATAL_ERROR "Headless mode entered the graphical startup path")
    endif()
    set(${name} "${output}" PARENT_SCOPE)
endfunction()
run_summary(first --seed 424242 --scene regression --checkpoint four-chunk --test-edits)
run_summary(second --seed 424242 --scene regression --checkpoint four-chunk --test-edits)
if(NOT "${first}" STREQUAL "${second}")
    message(FATAL_ERROR "Separate processes produced different world summaries")
endif()
message(STATUS "Full 441-chunk scene and edit summaries match across two headless processes")
