function(symocraft_input_comparison target backend)
    get_filename_component(root "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/../../.." ABSOLUTE)
    set(SYMOCRAFT_COMPARISON_SOURCE "${root}/out/m3-t2/baseline-input-001/source" CACHE PATH "Frozen camera and GLFW input")
    set(SYMOCRAFT_COMPARISON_BUILD "${root}/out/m3-t2/build/glfw-release" CACHE PATH "Matching frozen Release archives")
    if(CMAKE_CONFIGURATION_TYPES)
        set_target_properties(${target} PROPERTIES EXCLUDE_FROM_DEFAULT_BUILD_DEBUG TRUE)
    elseif(NOT CMAKE_BUILD_TYPE STREQUAL "Release")
        message(FATAL_ERROR "The continuous comparison imports the frozen Release camera; use Release")
    endif()
    set(SYMOCRAFT_REPOSITORY_ROOT "${SYMOCRAFT_COMPARISON_SOURCE}")
    include("${SYMOCRAFT_COMPARISON_SOURCE}/cmake/ThirdPartyHeaders.cmake")
    symocraft_header_view(${target}_glm_headers glm)
    foreach(dependency IN ITEMS foundation ecs simulation world yaml)
        if(dependency STREQUAL "yaml")
            set(archive "${SYMOCRAFT_COMPARISON_BUILD}/symocraft_yaml.lib")
        else()
            set(archive "${SYMOCRAFT_COMPARISON_BUILD}/game/modules/${dependency}/symocraft_${dependency}.lib")
        endif()
        if(NOT EXISTS "${archive}")
            message(FATAL_ERROR "Missing actual frozen camera dependency: ${archive}")
        endif()
        add_library(${target}_${dependency} STATIC IMPORTED)
        set_target_properties(${target}_${dependency} PROPERTIES IMPORTED_LOCATION "${archive}")
        target_link_libraries(${target} PRIVATE ${target}_${dependency})
    endforeach()
    foreach(module IN ITEMS foundation ecs scene world simulation platform)
        target_include_directories(${target} PRIVATE "${SYMOCRAFT_COMPARISON_SOURCE}/game/modules/${module}/include")
    endforeach()
    target_sources(${target} PRIVATE "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/comparison.cpp")
    target_include_directories(${target} PRIVATE "${CMAKE_CURRENT_FUNCTION_LIST_DIR}")
    target_link_libraries(${target} PRIVATE ${target}_glm_headers user32)
    target_compile_features(${target} PRIVATE cxx_std_20)
    target_compile_options(${target} PRIVATE /W4 /utf-8)
    target_compile_definitions(${target} PRIVATE SYMOCRAFT_COMPARISON_BACKEND="${backend}")
endfunction()
