if(NOT DEFINED BUILD_DIRECTORY)
    message(FATAL_ERROR "Pass the standalone CPU candidate build directory")
endif()
file(READ "${BUILD_DIRECTORY}/CMakeCache.txt" cache)
foreach(setting IN ITEMS "SYMOCRAFT_CPU_ONLY:BOOL=ON" "SYMOCRAFT_BUILD_GAME:BOOL=OFF" "SYMOCRAFT_BUILD_BENCHMARK:BOOL=OFF")
    string(FIND "${cache}" "${setting}" found)
    if(found EQUAL -1)
        message(FATAL_ERROR "Missing CPU isolation setting: ${setting}")
    endif()
endforeach()
if(cache MATCHES "\n(SDL[^:]*|Vulkan[^:]*|SYMOCRAFT_R1_DXC|SYMOCRAFT_R1_(d3d12|dxgi)_LIBRARY):")
    message(FATAL_ERROR "The CPU-only cache discovered a graphics/window dependency")
endif()

file(READ "${BUILD_DIRECTORY}/compile_commands.json" commands)
string(JSON count LENGTH "${commands}")
if(count LESS 3)
    message(FATAL_ERROR "Missing real CPU compiler commands")
endif()
math(EXPR last "${count} - 1")
foreach(index RANGE 0 ${last})
    string(JSON command GET "${commands}" ${index} command)
    string(REPLACE "\\" "/" command "${command}")
    string(TOLOWER "${command}" command)
    if(command MATCHES "vendor/(sdl3|glfw|glad)/|game/modules/(renderer|platform)/(src|include)|sdl_main_handled|vk_use_platform|vk_no_prototypes|glm_force_depth_zero_to_one|glm_force_left_handed")
        message(FATAL_ERROR "CPU consumer received a graphics/window path or backend macro: ${command}")
    endif()
endforeach()
file(READ "${BUILD_DIRECTORY}/build.ninja" graph)
string(TOLOWER "${graph}" graph)
if(graph MATCHES "[ /\\](d3d12|dxgi|dxguid|vulkan-1|glad|glfw3|sdl3-static)\\.lib")
    message(FATAL_ERROR "CPU consumers link a graphics/window library")
endif()
message(STATUS "R1 CPU cache, compiler paths/macros, and actual Ninja link graph are graphics-independent")
