add_library(symocraft_foundation STATIC src/document.cpp src/files.cpp src/legacy/AmoBase.cpp)
target_include_directories(symocraft_foundation PUBLIC "${CMAKE_CURRENT_SOURCE_DIR}/include" PRIVATE "${CMAKE_CURRENT_SOURCE_DIR}/src")
target_link_libraries(symocraft_foundation PUBLIC symocraft_math)
target_compile_features(symocraft_foundation PUBLIC cxx_std_20)
target_compile_options(symocraft_foundation PRIVATE /utf-8 /W4)
