include_guard(GLOBAL)

set(SYMOCRAFT_MODULE_NAMES foundation scene assets world ecs simulation platform renderer telemetry)
set(SYMOCRAFT_ALLOWED_foundation "")
set(SYMOCRAFT_ALLOWED_scene foundation)
set(SYMOCRAFT_ALLOWED_assets foundation)
set(SYMOCRAFT_ALLOWED_world foundation scene)
set(SYMOCRAFT_ALLOWED_ecs foundation)
set(SYMOCRAFT_ALLOWED_simulation foundation scene ecs world)
set(SYMOCRAFT_ALLOWED_platform foundation)
set(SYMOCRAFT_ALLOWED_renderer foundation scene assets platform)
set(SYMOCRAFT_ALLOWED_telemetry foundation)
set(SYMOCRAFT_ALLOWED_app ${SYMOCRAFT_MODULE_NAMES})
set(SYMOCRAFT_ALLOWED_benchmark "")
set(SYMOCRAFT_EXTERNAL_foundation symocraft_math glm::glm)
set(SYMOCRAFT_EXTERNAL_scene "")
set(SYMOCRAFT_EXTERNAL_assets symocraft_image_decoder symocraft_stb_headers)
set(SYMOCRAFT_EXTERNAL_world symocraft_yaml symocraft_noise)
set(SYMOCRAFT_EXTERNAL_ecs "")
set(SYMOCRAFT_EXTERNAL_simulation "")
set(SYMOCRAFT_EXTERNAL_platform SDL3::SDL3-static)
set(SYMOCRAFT_EXTERNAL_renderer symocraft_glad symocraft_stb_headers symocraft_robin_hood)
set(SYMOCRAFT_EXTERNAL_telemetry symocraft_yaml)
set(SYMOCRAFT_PLATFORM_BRIDGE_HEADERS graphics_bridge.h native_bridge.h vulkan_bridge.h)

function(symocraft_check_source_file root module source)
    file(READ "${source}" content)
    file(STRINGS "${source}" includes REGEX "^[ \t]*#[ \t]*include[ \t]*[<\"]")
    file(RELATIVE_PATH relative "${root}" "${source}")
    get_filename_component(directory "${source}" DIRECTORY)
    foreach(line IN LISTS includes)
        string(REGEX REPLACE "^[ \t]*#[ \t]*include[ \t]*[<\"]([^>\"]+)[>\"].*$" "\\1" header "${line}")
        if(header MATCHES "(^|/)(test|tests|app)/" OR header STREQUAL "core.h" OR header MATCHES "^(core|renderer|world|input|playercontroller|camera)/")
            message(FATAL_ERROR "Boundary violation: ${relative} includes forbidden ${header}")
        endif()
        if(header MATCHES "^symocraft/([^/]+)/")
            set(dependency "${CMAKE_MATCH_1}")
            if(NOT dependency STREQUAL module AND NOT dependency IN_LIST SYMOCRAFT_ALLOWED_${module})
                message(FATAL_ERROR "Boundary violation: ${module} -> ${dependency} in ${relative}: ${header}")
            endif()
        endif()
        string(REPLACE "\\" "/" normalized_header "${header}")
        string(TOLOWER "${normalized_header}" normalized_header)
        if(normalized_header MATCHES "^glfw/")
            message(FATAL_ERROR "Boundary violation: retired GLFW headers cannot enter production: ${relative} -> ${header}")
        endif()
        if(normalized_header MATCHES "^sdl3/")
            if(NOT module STREQUAL "platform" OR NOT relative MATCHES "^game/modules/platform/src/" OR
               relative MATCHES "/src/graphics_bridge/.*\\.(h|hpp)$")
                message(FATAL_ERROR "Boundary violation: SDL headers are private to platform implementation: ${relative} -> ${header}")
            endif()
        endif()
        if(module IN_LIST SYMOCRAFT_MODULE_NAMES AND relative MATCHES "/include/" AND header MATCHES "^(glad/|GLFW/|[Ww]indows\\.h|d3d|dxgi|vulkan/|yaml-cpp/|stb/|fast_noise_lite/|robin_hood\\.h)")
            message(FATAL_ERROR "Boundary violation: public header ${relative} exposes SDK/parser/storage dependency ${header}")
        endif()
        if(NOT module STREQUAL "renderer" AND NOT module STREQUAL "platform" AND header MATCHES "^(glad/|GLFW/|d3d|dxgi|vulkan/)")
            message(FATAL_ERROR "Boundary violation: CPU module ${module} includes graphics SDK ${header}")
        endif()
        if((module STREQUAL "telemetry" OR module STREQUAL "world" OR module STREQUAL "simulation") AND header MATCHES "(^|/)([Ww]indows\\.h|[Pp]sapi\\.h)$")
            message(FATAL_ERROR "Boundary violation: ${module} includes OS sampling SDK ${header}")
        endif()
        get_filename_component(resolved "${header}" ABSOLUTE BASE_DIR "${directory}")
        file(TO_CMAKE_PATH "${resolved}" resolved)
        file(RELATIVE_PATH resolved_relative "${root}" "${resolved}")
        string(TOLOWER "${resolved_relative}" resolved_relative_lower)
        if(resolved_relative_lower MATCHES "^(vendor|lib)/glfw(/|$)")
            message(FATAL_ERROR "Boundary violation: retired GLFW include cannot enter production: ${relative} -> ${header}")
        endif()
        if(resolved_relative_lower MATCHES "^vendor/sdl3(/|$)")
            message(FATAL_ERROR "Boundary violation: direct SDL vendor include bypasses private target headers: ${relative} -> ${header}")
        endif()
        if(module STREQUAL "app")
            set(own_root "${root}/game/app/")
        elseif(module STREQUAL "benchmark")
            set(own_root "${root}/tools/benchmark/")
        else()
            set(own_root "${root}/game/modules/${module}/")
        endif()
        file(TO_CMAKE_PATH "${own_root}" own_root)
        if(EXISTS "${resolved}")
            string(FIND "${resolved}" "${own_root}" inside)
            if(NOT inside EQUAL 0 AND resolved MATCHES "/(game/(modules|app)|test)/")
                message(FATAL_ERROR "Boundary violation: relative cross-owner include ${relative} -> ${header}")
            endif()
        endif()
        foreach(other IN LISTS SYMOCRAFT_MODULE_NAMES)
            if(other STREQUAL module)
                continue()
            endif()
            if(EXISTS "${root}/game/modules/${other}/src/${header}" OR
               EXISTS "${root}/game/modules/${other}/src/graphics_bridge/${header}")
                if(module STREQUAL "renderer" AND other STREQUAL "platform" AND header IN_LIST SYMOCRAFT_PLATFORM_BRIDGE_HEADERS)
                    continue()
                endif()
                if(NOT EXISTS "${directory}/${header}" AND NOT EXISTS "${root}/game/modules/${module}/src/${header}")
                    message(FATAL_ERROR "Boundary violation: private include ${relative} -> ${other}/src/${header}")
                endif()
            endif()
        endforeach()
    endforeach()
    if(content MATCHES "#[ \t]*include[ \t]+[A-Za-z_]")
        message(FATAL_ERROR "Boundary violation: macro-generated includes are not permitted in ${relative}")
    endif()
endfunction()

function(symocraft_check_source_tree root)
    foreach(module IN LISTS SYMOCRAFT_MODULE_NAMES)
        file(GLOB_RECURSE sources
            "${root}/game/modules/${module}/*.h" "${root}/game/modules/${module}/*.hpp"
            "${root}/game/modules/${module}/*.cpp")
        foreach(source IN LISTS sources)
            symocraft_check_source_file("${root}" "${module}" "${source}")
        endforeach()
    endforeach()
    foreach(owner IN ITEMS app benchmark)
        if(owner STREQUAL "app")
            set(directory "${root}/game/app")
        else()
            set(directory "${root}/tools/benchmark")
        endif()
        file(GLOB_RECURSE sources "${directory}/*.h" "${directory}/*.hpp" "${directory}/*.cpp")
        foreach(source IN LISTS sources)
            symocraft_check_source_file("${root}" "${owner}" "${source}")
        endforeach()
    endforeach()
endfunction()

function(symocraft_collect_targets directory output)
    get_property(targets DIRECTORY "${directory}" PROPERTY BUILDSYSTEM_TARGETS)
    get_property(children DIRECTORY "${directory}" PROPERTY SUBDIRECTORIES)
    foreach(child IN LISTS children)
        symocraft_collect_targets("${child}" child_targets)
        list(APPEND targets ${child_targets})
    endforeach()
    set(${output} "${targets}" PARENT_SCOPE)
endfunction()

function(symocraft_check_cycle target stack)
    if(target IN_LIST stack)
        message(FATAL_ERROR "Boundary violation: cyclic production target dependency ${stack};${target}")
    endif()
    get_property(done GLOBAL PROPERTY "SYMOCRAFT_VISITED_${target}")
    if(done)
        return()
    endif()
    list(APPEND stack "${target}")
    get_property(dependencies GLOBAL PROPERTY "SYMOCRAFT_EDGES_${target}")
    foreach(dependency IN LISTS dependencies)
        symocraft_check_cycle("${dependency}" "${stack}")
    endforeach()
    set_property(GLOBAL PROPERTY "SYMOCRAFT_VISITED_${target}" TRUE)
endfunction()

function(symocraft_validate_boundaries)
    symocraft_check_source_tree("${SYMOCRAFT_REPOSITORY_ROOT}")
    symocraft_collect_targets("${CMAKE_SOURCE_DIR}" targets)
    set(graph "digraph SymoCraft {\n")
    set(manifest "target\ttype\tfile\n")
    set(edges "target\tproperty\tdependency\traw_reference\n")
    foreach(target IN LISTS targets)
        get_target_property(directory ${target} SOURCE_DIR)
        file(RELATIVE_PATH relative_directory "${SYMOCRAFT_REPOSITORY_ROOT}" "${directory}")
        string(TOLOWER "${target}" target_lower)
        string(TOLOWER "${relative_directory}" relative_directory_lower)
        if(target_lower MATCHES "^glfw($|[0-9_:-])" OR relative_directory_lower MATCHES "^(vendor|lib)/glfw(/|$)")
            message(FATAL_ERROR "Boundary violation: retired GLFW target cannot be configured: ${target}")
        endif()
        get_target_property(type ${target} TYPE)
        get_target_property(sources ${target} SOURCES)
        set(production FALSE)
        if(relative_directory MATCHES "^(game|tools/benchmark)(/|$)")
            set(production TRUE)
        endif()
        set(all_edges "")
        foreach(property IN ITEMS LINK_LIBRARIES INTERFACE_LINK_LIBRARIES)
            get_target_property(all_links ${target} ${property})
            foreach(link IN LISTS all_links)
                string(REGEX REPLACE "^\\$<LINK_ONLY:([^>]+)>$" "\\1" link "${link}")
                if(TARGET "${link}")
                    list(APPEND all_edges "${link}")
                endif()
            endforeach()
        endforeach()
        list(REMOVE_DUPLICATES all_edges)
        set_property(GLOBAL PROPERTY "SYMOCRAFT_EDGES_${target}" "${all_edges}")
        set(implementation_count 0)
        foreach(source IN LISTS sources)
            if(source MATCHES "\\.disabled$")
                message(FATAL_ERROR "Boundary violation: retired source ${source} entered target ${target}")
            endif()
            if(source MATCHES "\\.(cpp|c)$" AND NOT source MATCHES "^\\$<")
                get_filename_component(absolute "${source}" ABSOLUTE BASE_DIR "${directory}")
                file(TO_CMAKE_PATH "${absolute}" absolute)
                file(RELATIVE_PATH source_relative "${SYMOCRAFT_REPOSITORY_ROOT}" "${absolute}")
                if(source_relative MATCHES "^(game|tools/benchmark)/")
                    if(NOT production)
                        message(FATAL_ERROR "Boundary violation: test ${target} recompiles production source ${absolute}")
                    endif()
                    string(SHA256 key "${absolute}")
                    get_property(owner GLOBAL PROPERTY "SYMOCRAFT_SOURCE_${key}")
                    if(owner AND NOT owner STREQUAL target)
                        message(FATAL_ERROR "Boundary violation: duplicate production source ${absolute}: ${owner}, ${target}")
                    endif()
                    set_property(GLOBAL PROPERTY "SYMOCRAFT_SOURCE_${key}" "${target}")
                    math(EXPR implementation_count "${implementation_count} + 1")
                    file(TO_CMAKE_PATH "${directory}/" owner_root)
                    string(FIND "${absolute}" "${owner_root}" owned_prefix)
                    if(NOT owned_prefix EQUAL 0)
                        message(FATAL_ERROR "Boundary violation: ${target} compiles source outside its owner directory: ${absolute}")
                    endif()
                    file(RELATIVE_PATH relative "${SYMOCRAFT_REPOSITORY_ROOT}" "${absolute}")
                    string(APPEND manifest "${target}\t${type}\t${relative}\n")
                elseif(production AND source_relative MATCHES "^test/")
                    message(FATAL_ERROR "Boundary violation: production ${target} compiles test source ${absolute}")
                endif()
            endif()
        endforeach()
        if(NOT production)
            continue()
        endif()
        if(relative_directory MATCHES "^game/modules/([^/]+)$")
            set(module "${CMAKE_MATCH_1}")
            if(module STREQUAL "scene")
                if(NOT type STREQUAL "INTERFACE_LIBRARY")
                    message(FATAL_ERROR "Boundary violation: scene must be an INTERFACE target")
                endif()
            elseif(NOT type STREQUAL "STATIC_LIBRARY" OR implementation_count EQUAL 0)
                message(FATAL_ERROR "Boundary violation: ${target} must own a real STATIC implementation")
            endif()
        else()
            set(module "")
        endif()
        foreach(property IN ITEMS INCLUDE_DIRECTORIES INTERFACE_INCLUDE_DIRECTORIES)
            get_target_property(paths ${target} ${property})
            foreach(path IN LISTS paths)
                if(IS_ABSOLUTE "${path}")
                    get_filename_component(path "${path}" ABSOLUTE)
                    file(TO_CMAKE_PATH "${path}" path)
                    file(RELATIVE_PATH include_relative "${SYMOCRAFT_REPOSITORY_ROOT}" "${path}")
                    if(include_relative MATCHES "^test(/|$)")
                        message(FATAL_ERROR "Boundary violation: production ${target} gains test include path ${path}")
                    endif()
                endif()
                if(path STREQUAL "${SYMOCRAFT_REPOSITORY_ROOT}" OR path STREQUAL "${SYMOCRAFT_REPOSITORY_ROOT}/vendor" OR path STREQUAL "${SYMOCRAFT_REPOSITORY_ROOT}/include")
                    message(FATAL_ERROR "Boundary violation: ${target} exposes broad include root ${path}")
                endif()
                string(TOLOWER "${path}" path_lower)
                if(path_lower MATCHES "/(vendor|lib)/glfw(/|$)")
                    message(FATAL_ERROR "Boundary violation: production ${target} gains retired GLFW include path ${path}")
                endif()
                if(path MATCHES "/vendor/sdl3(/|$)")
                    if(NOT target STREQUAL "symocraft_platform" OR property STREQUAL "INTERFACE_INCLUDE_DIRECTORIES")
                        message(FATAL_ERROR "Boundary violation: ${target} exposes private SDL include path ${path}")
                    endif()
                endif()
                if(module AND path MATCHES "/game/modules/([^/]+)/src($|/)")
                    set(owner "${CMAKE_MATCH_1}")
                    if(property STREQUAL "INTERFACE_INCLUDE_DIRECTORIES")
                        message(FATAL_ERROR "Boundary violation: ${target} publishes private implementation headers ${path}")
                    endif()
                    if(NOT owner STREQUAL module)
                        if(NOT (module STREQUAL "renderer" AND owner STREQUAL "platform" AND property STREQUAL "INCLUDE_DIRECTORIES" AND path MATCHES "/platform/src/graphics_bridge$"))
                            message(FATAL_ERROR "Boundary violation: ${target} exposes another module's private path ${path}")
                        endif()
                    endif()
                endif()
            endforeach()
        endforeach()
        set(target_edges "")
        foreach(property IN ITEMS LINK_LIBRARIES INTERFACE_LINK_LIBRARIES)
            get_target_property(links ${target} ${property})
            foreach(link IN LISTS links)
                set(raw_reference "${link}")
                string(TOLOWER "${raw_reference}" reference_lower)
                if(reference_lower MATCHES "(^|[^a-z0-9_])glfw([0-9_.:]|$|[^a-z0-9_])")
                    message(FATAL_ERROR "Boundary violation: retired GLFW link cannot enter production: ${target} -> ${raw_reference}")
                endif()
                set(link_only FALSE)
                if(link MATCHES "^\\$<LINK_ONLY:")
                    set(link_only TRUE)
                endif()
                string(REGEX REPLACE "^\\$<LINK_ONLY:([^>]+)>$" "\\1" link "${link}")
                if(link MATCHES "SDL3(::|-)" AND NOT TARGET "${link}")
                    message(FATAL_ERROR "Boundary violation: SDL target references require a direct approved target: ${target} -> ${raw_reference}")
                endif()
                if(NOT TARGET "${link}")
                    continue()
                endif()
                get_target_property(link_directory ${link} SOURCE_DIR)
                file(RELATIVE_PATH link_relative "${SYMOCRAFT_REPOSITORY_ROOT}" "${link_directory}")
                if(link MATCHES "^SDL3($|::|-)" OR link_relative MATCHES "^vendor/sdl3(/|$)")
                    if(NOT target STREQUAL "symocraft_platform" OR
                       (property STREQUAL "INTERFACE_LINK_LIBRARIES" AND NOT link_only))
                        message(FATAL_ERROR "Boundary violation: SDL target is private to symocraft_platform: ${target} -> ${raw_reference}")
                    endif()
                endif()
                if(link_relative MATCHES "^test(/|$)")
                    message(FATAL_ERROR "Boundary violation: production ${target} -> test ${link}")
                endif()
                if(module AND link_relative MATCHES "^game/app($|/)")
                    message(FATAL_ERROR "Boundary violation: module ${target} -> app ${link}")
                endif()
                string(REGEX REPLACE "^symocraft_" "" dependency "${link}")
                if(module AND dependency IN_LIST SYMOCRAFT_MODULE_NAMES AND NOT dependency STREQUAL module AND NOT dependency IN_LIST SYMOCRAFT_ALLOWED_${module})
                    message(FATAL_ERROR "Boundary violation: target ${target} -> ${link}")
                endif()
                if(module AND NOT dependency IN_LIST SYMOCRAFT_MODULE_NAMES AND NOT link IN_LIST SYMOCRAFT_EXTERNAL_${module})
                    message(FATAL_ERROR "Boundary violation: unauthorized external target ${target} -> ${link}")
                endif()
                if(module AND property STREQUAL "INTERFACE_LINK_LIBRARIES" AND NOT link_only AND
                   NOT dependency IN_LIST SYMOCRAFT_MODULE_NAMES AND NOT link MATCHES "^(symocraft_math|glm::glm)$")
                    message(FATAL_ERROR "Boundary violation: ${target} publishes private third-party usage requirements ${link}")
                endif()
                if(target MATCHES "^(benchmark_core|SymoCraftBenchmark)$" AND link_relative MATCHES "^game(/|$)")
                    message(FATAL_ERROR "Boundary violation: independent benchmark ${target} -> game ${link}")
                endif()
                if(relative_directory MATCHES "^game(/|$)" AND link_relative MATCHES "^tools/benchmark(/|$)")
                    message(FATAL_ERROR "Boundary violation: game ${target} -> independent benchmark ${link}")
                endif()
                list(APPEND target_edges "${link}")
                set(edge_label "${property}")
                if(link_only)
                    string(APPEND edge_label " (LINK_ONLY)")
                endif()
                string(APPEND graph "  \"${target}\" -> \"${link}\" [label=\"${edge_label}\"];\n")
                string(APPEND edges "${target}\t${property}\t${link}\t${raw_reference}\n")
            endforeach()
        endforeach()
        list(REMOVE_DUPLICATES target_edges)
        set_property(GLOBAL PROPERTY "SYMOCRAFT_EDGES_${target}" "${target_edges}")
    endforeach()
    foreach(target IN LISTS targets)
        symocraft_check_cycle("${target}" "")
    endforeach()
    file(GLOB_RECURSE owned_sources CONFIGURE_DEPENDS
        "${SYMOCRAFT_REPOSITORY_ROOT}/game/*.cpp" "${SYMOCRAFT_REPOSITORY_ROOT}/tools/benchmark/*.cpp")
    foreach(source IN LISTS owned_sources)
        if((source MATCHES "/tools/benchmark/" AND NOT TARGET benchmark_core) OR
           (source MATCHES "/game/" AND NOT TARGET symocraft_foundation) OR
           (source MATCHES "/game/(app|modules/(platform|renderer))/" AND NOT TARGET SymoCraft))
            continue()
        endif()
        string(SHA256 key "${source}")
        get_property(owner GLOBAL PROPERTY "SYMOCRAFT_SOURCE_${key}")
        if(NOT owner)
            message(FATAL_ERROR "Boundary violation: production source has no target owner: ${source}")
        endif()
    endforeach()
    string(APPEND graph "}\n")
    file(WRITE "${CMAKE_BINARY_DIR}/production-targets.dot" "${graph}")
    file(WRITE "${CMAKE_BINARY_DIR}/production-sources.tsv" "${manifest}")
    file(WRITE "${CMAKE_BINARY_DIR}/production-dependencies.tsv" "${edges}")
endfunction()
