include_guard(GLOBAL)
function(symocraft_public_header_tests)
    set(manifest "")
    foreach(module IN ITEMS foundation scene assets world ecs simulation platform renderer telemetry)
        if(NOT TARGET symocraft_${module})
            continue()
        endif()
        set(root "${SYMOCRAFT_REPOSITORY_ROOT}/game/modules/${module}/include")
        file(GLOB_RECURSE headers CONFIGURE_DEPENDS RELATIVE "${root}" "${root}/*.h" "${root}/*.hpp")
        foreach(header IN LISTS headers)
            string(MAKE_C_IDENTIFIER "header_${module}_${header}" target)
            set(source "${CMAKE_CURRENT_BINARY_DIR}/public-headers/${target}.cpp")
            file(GENERATE OUTPUT "${source}" CONTENT "#include <${header}>\nint main() { return 0; }\n")
            add_executable(${target} "${source}")
            target_link_libraries(${target} PRIVATE symocraft_${module})
            target_compile_options(${target} PRIVATE /utf-8)
            add_test(NAME "architecture.public_header.${module}.${header}" COMMAND ${target})
            string(APPEND manifest "${module}\t${header}\t${target}\n")
        endforeach()
    endforeach()
    file(WRITE "${CMAKE_BINARY_DIR}/public-headers.tsv" "${manifest}")
endfunction()
