include_guard(GLOBAL)
include("${CMAKE_CURRENT_LIST_DIR}/ThirdPartyHeaders.cmake")

symocraft_header_view(symocraft_math glm)
add_library(glm::glm ALIAS symocraft_math)
symocraft_header_view(symocraft_image_decoder stb/stb_image.h)
symocraft_header_view(symocraft_image_writer stb/stb_image_write.h)
add_library(symocraft_stb_headers ALIAS symocraft_image_writer)
symocraft_header_view(symocraft_noise fast_noise_lite)
symocraft_header_view(symocraft_robin_hood robin_hood.h)

function(symocraft_add_graphics_dependencies)
    set(BUILD_SHARED_LIBS OFF)
    set(SDL_SHARED OFF CACHE BOOL "Build SDL shared library" FORCE)
    set(SDL_STATIC ON CACHE BOOL "Build SDL static library" FORCE)
    set(SDL_LIBC ON CACHE BOOL "Use the existing MSVC C runtime policy" FORCE)
    set(SDL_TEST_LIBRARY OFF CACHE BOOL "Build SDL's internal test library" FORCE)
    set(SDL_TESTS OFF CACHE BOOL "Build SDL's internal tests" FORCE)
    set(SDL_EXAMPLES OFF CACHE BOOL "Build SDL's examples" FORCE)
    set(SDL_INSTALL OFF CACHE BOOL "Install SDL as a standalone package" FORCE)
    foreach(subsystem IN ITEMS AUDIO RENDER GPU CAMERA JOYSTICK HAPTIC HIDAPI POWER SENSOR DIALOG TRAY)
        set(SDL_${subsystem} OFF CACHE BOOL "Not part of the platform window/input scope" FORCE)
    endforeach()
    set(SDL_VIDEO ON CACHE BOOL "Enable real window and input support" FORCE)
    set(SDL_OPENGL ON CACHE BOOL "Enable the desktop OpenGL bridge" FORCE)
    set(SDL_OPENGLES OFF CACHE BOOL "OpenGL ES is outside the platform scope" FORCE)
    set(SDL_DUMMYVIDEO OFF CACHE BOOL "Do not substitute a dummy video driver" FORCE)
    set(SDL_OFFSCREEN OFF CACHE BOOL "Do not substitute an offscreen video driver" FORCE)
    set(SDL_VULKAN ON CACHE BOOL "Enable SDL's dynamically loaded Vulkan window bridge" FORCE)
    add_subdirectory("${SYMOCRAFT_REPOSITORY_ROOT}/vendor/sdl3" "${PROJECT_BINARY_DIR}/vendor/sdl3" EXCLUDE_FROM_ALL)

    symocraft_header_view(symocraft_glad_headers glad/glad.h KHR/khrplatform.h)
    add_library(symocraft_glad STATIC "${SYMOCRAFT_REPOSITORY_ROOT}/vendor/glad/glad.c")
    target_link_libraries(symocraft_glad PUBLIC symocraft_glad_headers)
    target_compile_options(symocraft_glad PRIVATE /utf-8)
endfunction()
