include_guard(GLOBAL)
include("${CMAKE_CURRENT_LIST_DIR}/ThirdPartyHeaders.cmake")

symocraft_header_view(symocraft_math glm)
add_library(glm::glm ALIAS symocraft_math)
symocraft_header_view(symocraft_image_decoder stb/stb_image.h)
symocraft_header_view(symocraft_image_writer stb/stb_image_write.h)
add_library(symocraft_stb_headers ALIAS symocraft_image_writer)
symocraft_header_view(symocraft_noise fast_noise_lite)
symocraft_header_view(symocraft_robin_hood robin_hood.h)

function(symocraft_add_graphics_dependencies)
    set(BUILD_SHARED_LIBS OFF)
    set(GLFW_BUILD_EXAMPLES OFF CACHE BOOL "Build GLFW examples" FORCE)
    set(GLFW_BUILD_TESTS OFF CACHE BOOL "Build GLFW tests" FORCE)
    set(GLFW_BUILD_DOCS OFF CACHE BOOL "Build GLFW documentation" FORCE)
    set(GLFW_INSTALL OFF CACHE BOOL "Install GLFW" FORCE)
    add_subdirectory("${SYMOCRAFT_REPOSITORY_ROOT}/vendor/glfw" "${PROJECT_BINARY_DIR}/vendor/glfw" EXCLUDE_FROM_ALL)
    symocraft_header_view(symocraft_glad_headers glad/glad.h KHR/khrplatform.h)
    add_library(symocraft_glad STATIC "${SYMOCRAFT_REPOSITORY_ROOT}/vendor/glad/glad.c")
    target_link_libraries(symocraft_glad PUBLIC symocraft_glad_headers)
    target_compile_options(symocraft_glad PRIVATE /utf-8)
endfunction()
