cmake_minimum_required(VERSION 3.22)
file(MAKE_DIRECTORY "${OUTPUT}")
set(cases world-renderer simulation-platform module-app production-test private-cross-include public-sdk
    sdl-platform-source sdl-platform-public sdl-platform-bridge sdl-platform-bridge-source sdl-renderer-source sdl-app-source
    sdl-cpu-source sdl-relative-vendor sdl-relative-platform-vendor
    glfw-platform-source glfw-renderer-source glfw-app-source glfw-cpu-source glfw-platform-public glfw-relative-vendor)
foreach(case IN LISTS cases)
    set(root "${OUTPUT}/${case}")
    file(MAKE_DIRECTORY "${root}/game/modules/world/src" "${root}/game/modules/simulation/src"
        "${root}/game/modules/renderer/src" "${root}/game/modules/world/include/symocraft/world"
        "${root}/game/modules/platform/src/graphics_bridge" "${root}/game/modules/platform/include/symocraft/platform"
        "${root}/game/app/src" "${root}/vendor/sdl3/include/SDL3" "${root}/vendor/glfw/include/GLFW")
    set(module world)
    set(path "${root}/game/modules/world/src/rejected.cpp")
    set(accepted FALSE)
    if(case STREQUAL "world-renderer")
        set(content "#include <symocraft/renderer/renderer.h>\n")
    elseif(case STREQUAL "simulation-platform")
        set(module simulation)
        set(path "${root}/game/modules/simulation/src/rejected.cpp")
        set(content "#include <symocraft/platform/window.h>\n")
    elseif(case STREQUAL "module-app")
        set(content "#include <app/application.h>\n")
    elseif(case STREQUAL "production-test")
        set(content "#include <test/support/fixture.h>\n")
    elseif(case STREQUAL "private-cross-include")
        file(WRITE "${root}/game/modules/renderer/src/batch.hpp" "#pragma once\n")
        set(content "#include \"../../renderer/src/batch.hpp\"\n")
    elseif(case MATCHES "^glfw-")
        set(content "#include <GLFW/glfw3.h>\n")
        if(case MATCHES "^glfw-platform" OR case STREQUAL "glfw-relative-vendor")
            set(module platform)
            set(path "${root}/game/modules/platform/src/rejected.cpp")
        elseif(case STREQUAL "glfw-renderer-source")
            set(module renderer)
            set(path "${root}/game/modules/renderer/src/rejected.cpp")
        elseif(case STREQUAL "glfw-app-source")
            set(module app)
            set(path "${root}/game/app/src/rejected.cpp")
        endif()
        if(case STREQUAL "glfw-platform-public")
            set(path "${root}/game/modules/platform/include/symocraft/platform/rejected.h")
        elseif(case STREQUAL "glfw-relative-vendor")
            file(WRITE "${root}/vendor/glfw/include/GLFW/glfw3.h" "#pragma once\n")
            get_filename_component(directory "${path}" DIRECTORY)
            file(RELATIVE_PATH vendor_header "${directory}" "${root}/vendor/glfw/include/GLFW/glfw3.h")
            set(content "#include \"${vendor_header}\"\n")
        endif()
    elseif(case MATCHES "^sdl-")
        set(content "#include <SDL3/SDL.h>\n")
        if(case MATCHES "^sdl-platform" OR case STREQUAL "sdl-relative-platform-vendor")
            set(module platform)
            set(path "${root}/game/modules/platform/src/rejected.cpp")
        elseif(case STREQUAL "sdl-renderer-source")
            set(module renderer)
            set(path "${root}/game/modules/renderer/src/rejected.cpp")
        elseif(case STREQUAL "sdl-app-source")
            set(module app)
            set(path "${root}/game/app/src/rejected.cpp")
        endif()
        if(case STREQUAL "sdl-platform-source")
            set(accepted TRUE)
        elseif(case STREQUAL "sdl-platform-public")
            set(path "${root}/game/modules/platform/include/symocraft/platform/rejected.h")
        elseif(case STREQUAL "sdl-platform-bridge")
            set(path "${root}/game/modules/platform/src/graphics_bridge/rejected.h")
        elseif(case STREQUAL "sdl-platform-bridge-source")
            set(path "${root}/game/modules/platform/src/graphics_bridge/accepted.cpp")
            set(accepted TRUE)
        elseif(case MATCHES "^sdl-relative-")
            file(WRITE "${root}/vendor/sdl3/include/SDL3/SDL.h" "#pragma once\n")
            get_filename_component(directory "${path}" DIRECTORY)
            file(RELATIVE_PATH vendor_header "${directory}" "${root}/vendor/sdl3/include/SDL3/SDL.h")
            set(content "#include \"${vendor_header}\"\n")
        endif()
    else()
        set(path "${root}/game/modules/world/include/symocraft/world/rejected.h")
        set(content "#include <yaml-cpp/yaml.h>\n")
    endif()
    file(WRITE "${path}" "${content}")
    file(WRITE "${root}/probe.cmake"
        "cmake_minimum_required(VERSION 3.22)\ninclude(\"${REPO}/cmake/ModuleBoundaries.cmake\")\nsymocraft_check_source_file(\"${root}\" \"${module}\" \"${path}\")\n")
    execute_process(COMMAND "${CMAKE_COMMAND}" -P "${root}/probe.cmake"
        RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
    file(WRITE "${root}/result.log" "${output}${error}")
    if(accepted)
        if(NOT result EQUAL 0)
            message(FATAL_ERROR "Positive case ${case} was rejected: ${output}${error}")
        endif()
        message(STATUS "Accepted ${case}")
    elseif(result EQUAL 0 OR NOT error MATCHES "Boundary violation")
        message(FATAL_ERROR "Negative case ${case} was not rejected by the real production boundary checker: ${output}${error}")
    else()
        message(STATUS "Rejected ${case}")
    endif()
endforeach()

# Retired GLFW must not be configured, linked or made visible by active targets.
foreach(case IN ITEMS glfw-target-unlinked glfw-target-renamed glfw-link-platform
    glfw-link-platform-expression glfw-link-app glfw-link-library
    glfw-path-platform-private glfw-path-platform-public glfw-path-app glfw-path-library)
    set(root "${OUTPUT}/${case}")
    file(MAKE_DIRECTORY "${root}/vendor/glfw" "${root}/lib/glfw" "${root}/game/modules/platform/src" "${root}/game/app/src")
    set(cmakelists "cmake_minimum_required(VERSION 3.22)\nproject(GlfwRetirement LANGUAGES NONE)\nset(SYMOCRAFT_REPOSITORY_ROOT \"${root}\")\n")
    if(case MATCHES "^glfw-target-")
        if(case STREQUAL "glfw-target-unlinked")
            set(retired_target glfw)
        else()
            set(retired_target historical_window_library)
        endif()
        file(WRITE "${root}/vendor/glfw/CMakeLists.txt" "add_library(${retired_target} INTERFACE)\n")
        string(APPEND cmakelists "add_subdirectory(vendor/glfw EXCLUDE_FROM_ALL)\n")
        set(expected "retired GLFW target cannot be configured")
    else()
        if(case MATCHES "app$")
            set(directory "${root}/game/app")
            set(target symocraft_startup)
        else()
            set(directory "${root}/game/modules/platform")
            set(target symocraft_platform)
        endif()
        file(WRITE "${directory}/src/owned.cpp" "int owned() { return 0; }\n")
        set(owner_cmake "add_library(${target} STATIC src/owned.cpp)\nset_target_properties(${target} PROPERTIES LINKER_LANGUAGE CXX)\n")
        if(case MATCHES "^glfw-link-")
            if(case MATCHES "expression$")
                set(reference "$<BUILD_INTERFACE:glfw>")
            elseif(case MATCHES "library$")
                set(reference "${root}/lib/glfw/glfw3.lib")
            else()
                set(reference glfw)
            endif()
            string(APPEND owner_cmake "target_link_libraries(${target} PRIVATE \"${reference}\")\n")
            set(expected "retired GLFW link cannot enter production")
        else()
            if(case MATCHES "public$")
                set(scope PUBLIC)
            else()
                set(scope PRIVATE)
            endif()
            if(case MATCHES "library$")
                set(include_path "${root}/lib/glfw")
            else()
                set(include_path "${root}/vendor/glfw/include")
            endif()
            string(APPEND owner_cmake "target_include_directories(${target} ${scope} \"${include_path}\")\n")
            set(expected "gains retired GLFW")
        endif()
        file(WRITE "${directory}/CMakeLists.txt" "${owner_cmake}")
        file(RELATIVE_PATH owner_directory "${root}" "${directory}")
        string(APPEND cmakelists "add_subdirectory(${owner_directory})\n")
    endif()
    string(APPEND cmakelists "include(\"${REPO}/cmake/ModuleBoundaries.cmake\")\nsymocraft_validate_boundaries()\n")
    file(WRITE "${root}/CMakeLists.txt" "${cmakelists}")
    execute_process(COMMAND "${CMAKE_COMMAND}" -S "${root}" -B "${root}/build" -G Ninja "-DCMAKE_MAKE_PROGRAM=${NINJA}"
        RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
    file(WRITE "${root}/result.log" "${output}${error}")
    if(result EQUAL 0 OR NOT error MATCHES "${expected}")
        message(FATAL_ERROR "GLFW retirement case ${case} failed for the wrong reason: ${output}${error}")
    endif()
    message(STATUS "Rejected ${case} during real CMake configuration")
endforeach()

# Only canonical private bridge headers are granted to the renderer.
foreach(case IN ITEMS bridge-renderer-native bridge-renderer-vulkan bridge-renderer-relative-native
    bridge-cpu-native bridge-cpu-vulkan bridge-app-native bridge-app-vulkan
    bridge-public-windows bridge-public-vulkan)
    set(root "${OUTPUT}/${case}")
    file(MAKE_DIRECTORY "${root}/game/modules/platform/src/graphics_bridge"
        "${root}/game/modules/renderer/src" "${root}/game/modules/world/src"
        "${root}/game/app/src" "${root}/game/modules/platform/include/symocraft/platform")
    file(WRITE "${root}/game/modules/platform/src/graphics_bridge/native_bridge.h" "#pragma once\n#include <Windows.h>\n")
    file(WRITE "${root}/game/modules/platform/src/graphics_bridge/vulkan_bridge.h" "#pragma once\n#include <vulkan/vulkan_core.h>\n")
    set(module renderer)
    set(path "${root}/game/modules/renderer/src/probe.cpp")
    set(accepted FALSE)
    if(case MATCHES "vulkan$")
        set(header vulkan_bridge.h)
    else()
        set(header native_bridge.h)
    endif()
    set(content "#include <${header}>\n")
    if(case MATCHES "^bridge-renderer-(native|vulkan)$")
        set(accepted TRUE)
    elseif(case STREQUAL "bridge-renderer-relative-native")
        set(content "#include \"../../platform/src/graphics_bridge/native_bridge.h\"\n")
    elseif(case MATCHES "^bridge-cpu-")
        set(module world)
        set(path "${root}/game/modules/world/src/probe.cpp")
    elseif(case MATCHES "^bridge-app-")
        set(module app)
        set(path "${root}/game/app/src/probe.cpp")
    else()
        set(module platform)
        set(path "${root}/game/modules/platform/include/symocraft/platform/probe.h")
        if(case STREQUAL "bridge-public-windows")
            set(content "#include <Windows.h>\n")
        else()
            set(content "#include <vulkan/vulkan_core.h>\n")
        endif()
    endif()
    file(WRITE "${path}" "${content}")
    file(WRITE "${root}/probe.cmake"
        "cmake_minimum_required(VERSION 3.22)\ninclude(\"${REPO}/cmake/ModuleBoundaries.cmake\")\nsymocraft_check_source_file(\"${root}\" \"${module}\" \"${path}\")\n")
    execute_process(COMMAND "${CMAKE_COMMAND}" -P "${root}/probe.cmake"
        RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
    file(WRITE "${root}/result.log" "${output}${error}")
    if(accepted)
        if(NOT result EQUAL 0)
            message(FATAL_ERROR "Positive bridge case ${case} was rejected: ${output}${error}")
        endif()
        message(STATUS "Accepted ${case}")
    elseif(result EQUAL 0 OR NOT error MATCHES "Boundary violation")
        message(FATAL_ERROR "Negative bridge case ${case} was not rejected by the production checker: ${output}${error}")
    else()
        message(STATUS "Rejected ${case}")
    endif()
endforeach()

# SDL target authorization is platform-private, including static LINK_ONLY edges.
foreach(case IN ITEMS sdl-target-platform-private sdl-target-platform-public sdl-target-renderer
    sdl-target-app sdl-target-cpu sdl-target-platform-public-expression sdl-target-renderer-expression
    sdl-path-platform-public sdl-path-renderer sdl-path-app sdl-path-cpu)
    set(root "${OUTPUT}/${case}")
    file(MAKE_DIRECTORY "${root}/vendor/sdl3/include/SDL3" "${root}/game/modules/platform/src"
        "${root}/game/modules/renderer/src" "${root}/game/modules/world/src" "${root}/game/app")
    file(WRITE "${root}/vendor/sdl3/include/SDL3/SDL.h" "#pragma once\n")
    file(WRITE "${root}/vendor/sdl3/CMakeLists.txt"
        "add_library(SDL3-static INTERFACE)\nadd_library(SDL3::SDL3-static ALIAS SDL3-static)\ntarget_include_directories(SDL3-static INTERFACE \"${root}/vendor/sdl3/include\")\n")
    if(case MATCHES "platform")
        set(owner platform)
        set(target symocraft_platform)
    elseif(case MATCHES "renderer")
        set(owner renderer)
        set(target symocraft_renderer)
    elseif(case MATCHES "app")
        set(owner app)
        set(target symocraft_startup)
    else()
        set(owner world)
        set(target symocraft_world)
    endif()
    if(owner STREQUAL "app")
        set(directory "${root}/game/app")
    else()
        set(directory "${root}/game/modules/${owner}")
    endif()
    file(MAKE_DIRECTORY "${directory}/src")
    file(WRITE "${directory}/src/owned.cpp" "int owned() { return 0; }\n")
    set(owner_cmake "add_library(${target} STATIC src/owned.cpp)\nset_target_properties(${target} PROPERTIES LINKER_LANGUAGE CXX)\n")
    set(scope PRIVATE)
    if(case MATCHES "public($|-)")
        set(scope PUBLIC)
    endif()
    if(case MATCHES "^sdl-path-")
        string(APPEND owner_cmake "target_include_directories(${target} ${scope} \"${root}/vendor/sdl3/include\")\n")
        set(expected "exposes private SDL include path")
    elseif(case MATCHES "expression$")
        string(APPEND owner_cmake "target_link_libraries(${target} ${scope} $<BUILD_INTERFACE:SDL3::SDL3-static>)\n")
        set(expected "SDL target references require a direct approved target")
    else()
        string(APPEND owner_cmake "target_link_libraries(${target} ${scope} SDL3::SDL3-static)\n")
        set(expected "SDL target is private to symocraft_platform")
    endif()
    file(WRITE "${directory}/CMakeLists.txt" "${owner_cmake}")
    file(RELATIVE_PATH owner_directory "${root}" "${directory}")
    # These target-property fixtures configure only and need no installed compiler.
    file(WRITE "${root}/CMakeLists.txt"
        "cmake_minimum_required(VERSION 3.22)\nproject(SdlBoundary LANGUAGES NONE)\nset(CMAKE_CXX_ARCHIVE_CREATE \"<CMAKE_COMMAND> -E true\")\nset(CMAKE_CXX_ARCHIVE_FINISH \"<CMAKE_COMMAND> -E true\")\nset(SYMOCRAFT_REPOSITORY_ROOT \"${root}\")\nadd_subdirectory(vendor/sdl3)\nadd_subdirectory(${owner_directory})\ninclude(\"${REPO}/cmake/ModuleBoundaries.cmake\")\nsymocraft_validate_boundaries()\n")
    execute_process(COMMAND "${CMAKE_COMMAND}" -S "${root}" -B "${root}/build" -G Ninja "-DCMAKE_MAKE_PROGRAM=${NINJA}"
        RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
    file(WRITE "${root}/result.log" "${output}${error}")
    if(case STREQUAL "sdl-target-platform-private")
        if(NOT result EQUAL 0)
            message(FATAL_ERROR "SDL platform-private target was rejected: ${output}${error}")
        endif()
        message(STATUS "Accepted ${case} during real CMake configuration")
    elseif(result EQUAL 0 OR NOT error MATCHES "${expected}")
        message(FATAL_ERROR "SDL target case ${case} failed for the wrong reason: ${output}${error}")
    else()
        message(STATUS "Rejected ${case} during real CMake configuration")
    endif()
endforeach()

# Use actual CMake targets and the same configure-time validator as the product.
foreach(case IN ITEMS target-world-renderer target-simulation-platform target-module-app target-production-test broad-include duplicate-source target-cycle test-include target-game-benchmark public-private-path)
    set(root "${OUTPUT}/${case}")
    file(MAKE_DIRECTORY "${root}/game/modules/world/src" "${root}/game/modules/renderer/src"
        "${root}/game/modules/simulation/src" "${root}/game/modules/platform/src" "${root}/game/app" "${root}/test")
    set(cmakelists "cmake_minimum_required(VERSION 3.22)\nproject(NegativeBoundary LANGUAGES NONE)\nset(SYMOCRAFT_REPOSITORY_ROOT \"${root}\")\n")
    set(module world)
    if(case STREQUAL "target-simulation-platform")
        set(module simulation)
        set(dependency platform)
    elseif(case STREQUAL "target-world-renderer")
        set(dependency renderer)
    else()
        set(dependency "")
    endif()
    set(source "${root}/game/modules/${module}/src/owned.cpp")
    file(WRITE "${source}" "int owned() { return 0; }\n")
    set(module_cmake "add_library(symocraft_${module} STATIC src/owned.cpp)\nset_target_properties(symocraft_${module} PROPERTIES LINKER_LANGUAGE CXX)\n")
    if(dependency)
        file(WRITE "${root}/game/modules/${dependency}/src/owned.cpp" "int other() { return 0; }\n")
        file(WRITE "${root}/game/modules/${dependency}/CMakeLists.txt"
            "add_library(symocraft_${dependency} STATIC src/owned.cpp)\nset_target_properties(symocraft_${dependency} PROPERTIES LINKER_LANGUAGE CXX)\n")
        string(APPEND cmakelists "add_subdirectory(game/modules/${dependency})\n")
        string(APPEND module_cmake "target_link_libraries(symocraft_${module} PRIVATE symocraft_${dependency})\n")
        set(expected "Boundary violation: target")
    elseif(case STREQUAL "target-module-app")
        file(WRITE "${root}/game/app/CMakeLists.txt" "add_library(symocraft_startup INTERFACE)\n")
        string(APPEND cmakelists "add_subdirectory(game/app)\n")
        string(APPEND module_cmake "target_link_libraries(symocraft_world PRIVATE symocraft_startup)\n")
        set(expected "Boundary violation: module")
    elseif(case STREQUAL "target-production-test")
        file(WRITE "${root}/test/CMakeLists.txt" "add_library(test_fixture INTERFACE)\n")
        string(APPEND cmakelists "add_subdirectory(test)\n")
        string(APPEND module_cmake "target_link_libraries(symocraft_world PRIVATE test_fixture)\n")
        set(expected "Boundary violation: production")
    elseif(case STREQUAL "broad-include")
        string(APPEND module_cmake "target_include_directories(symocraft_world PUBLIC \"${root}/vendor\")\n")
        set(expected "Boundary violation: symocraft_world exposes broad")
    elseif(case STREQUAL "duplicate-source")
        string(APPEND module_cmake "add_library(duplicate STATIC src/owned.cpp)\nset_target_properties(duplicate PROPERTIES LINKER_LANGUAGE CXX)\n")
        set(expected "Boundary violation: duplicate production source")
    elseif(case STREQUAL "public-private-path")
        string(APPEND module_cmake "target_include_directories(symocraft_world PUBLIC \"${root}/game/modules/world/src\")\n")
        set(expected "Boundary violation: symocraft_world publishes private implementation")
    elseif(case STREQUAL "test-include")
        string(APPEND module_cmake "target_include_directories(symocraft_world PRIVATE \"${root}/test/support\")\n")
        set(expected "Boundary violation: production symocraft_world gains test include")
    elseif(case STREQUAL "target-game-benchmark")
        file(MAKE_DIRECTORY "${root}/tools/benchmark")
        file(WRITE "${root}/tools/benchmark/CMakeLists.txt" "add_library(benchmark_core INTERFACE)\n")
        file(WRITE "${root}/game/app/CMakeLists.txt" "add_library(symocraft_startup INTERFACE)\ntarget_link_libraries(symocraft_startup INTERFACE benchmark_core)\n")
        string(APPEND cmakelists "add_subdirectory(tools/benchmark)\nadd_subdirectory(game/app)\n")
        set(expected "Boundary violation: game symocraft_startup -> independent benchmark")
    else()
        string(APPEND module_cmake "target_link_libraries(symocraft_world PRIVATE symocraft_world)\n")
        set(expected "Boundary violation: cyclic production")
    endif()
    file(WRITE "${root}/game/modules/${module}/CMakeLists.txt" "${module_cmake}")
    string(APPEND cmakelists "add_subdirectory(game/modules/${module})\ninclude(\"${REPO}/cmake/ModuleBoundaries.cmake\")\nsymocraft_validate_boundaries()\n")
    file(WRITE "${root}/CMakeLists.txt" "${cmakelists}")
    execute_process(COMMAND "${CMAKE_COMMAND}" -S "${root}" -B "${root}/build" -G Ninja "-DCMAKE_MAKE_PROGRAM=${NINJA}"
        RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
    file(WRITE "${root}/result.log" "${output}${error}")
    if(result EQUAL 0 OR NOT error MATCHES "${expected}")
        message(FATAL_ERROR "Negative target case ${case} failed for the wrong reason: ${output}${error}")
    endif()
    message(STATUS "Rejected ${case} during real CMake configuration")
endforeach()
