cmake_minimum_required(VERSION 3.22)
file(MAKE_DIRECTORY "${OUTPUT}")
set(cases world-renderer simulation-platform module-app production-test private-cross-include public-sdk)
foreach(case IN LISTS cases)
    set(root "${OUTPUT}/${case}")
    file(MAKE_DIRECTORY "${root}/game/modules/world/src" "${root}/game/modules/simulation/src"
        "${root}/game/modules/renderer/src" "${root}/game/modules/world/include/symocraft/world")
    set(module world)
    set(path "${root}/game/modules/world/src/rejected.cpp")
    if(case STREQUAL "world-renderer")
        set(content "#include <symocraft/renderer/renderer.h>\n")
    elseif(case STREQUAL "simulation-platform")
        set(module simulation)
        set(path "${root}/game/modules/simulation/src/rejected.cpp")
        set(content "#include <symocraft/platform/window.h>\n")
    elseif(case STREQUAL "module-app")
        set(content "#include <app/application.h>\n")
    elseif(case STREQUAL "production-test")
        set(content "#include <test/support/fixture.h>\n")
    elseif(case STREQUAL "private-cross-include")
        file(WRITE "${root}/game/modules/renderer/src/batch.hpp" "#pragma once\n")
        set(content "#include \"../../renderer/src/batch.hpp\"\n")
    else()
        set(path "${root}/game/modules/world/include/symocraft/world/rejected.h")
        set(content "#include <yaml-cpp/yaml.h>\n")
    endif()
    file(WRITE "${path}" "${content}")
    file(WRITE "${root}/probe.cmake"
        "cmake_minimum_required(VERSION 3.22)\ninclude(\"${REPO}/cmake/ModuleBoundaries.cmake\")\nsymocraft_check_source_file(\"${root}\" \"${module}\" \"${path}\")\n")
    execute_process(COMMAND "${CMAKE_COMMAND}" -P "${root}/probe.cmake"
        RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
    file(WRITE "${root}/result.log" "${output}${error}")
    if(result EQUAL 0 OR NOT error MATCHES "Boundary violation")
        message(FATAL_ERROR "Negative case ${case} was not rejected by the real production boundary checker: ${output}${error}")
    endif()
    message(STATUS "Rejected ${case}")
endforeach()

# Use actual CMake targets and the same configure-time validator as the product.
foreach(case IN ITEMS target-world-renderer target-simulation-platform target-module-app target-production-test broad-include duplicate-source target-cycle test-include target-game-benchmark public-private-path)
    set(root "${OUTPUT}/${case}")
    file(MAKE_DIRECTORY "${root}/game/modules/world/src" "${root}/game/modules/renderer/src"
        "${root}/game/modules/simulation/src" "${root}/game/modules/platform/src" "${root}/game/app" "${root}/test")
    set(cmakelists "cmake_minimum_required(VERSION 3.22)\nproject(NegativeBoundary LANGUAGES NONE)\nset(SYMOCRAFT_REPOSITORY_ROOT \"${root}\")\n")
    set(module world)
    if(case STREQUAL "target-simulation-platform")
        set(module simulation)
        set(dependency platform)
    elseif(case STREQUAL "target-world-renderer")
        set(dependency renderer)
    else()
        set(dependency "")
    endif()
    set(source "${root}/game/modules/${module}/src/owned.cpp")
    file(WRITE "${source}" "int owned() { return 0; }\n")
    set(module_cmake "add_library(symocraft_${module} STATIC src/owned.cpp)\nset_target_properties(symocraft_${module} PROPERTIES LINKER_LANGUAGE CXX)\n")
    if(dependency)
        file(WRITE "${root}/game/modules/${dependency}/src/owned.cpp" "int other() { return 0; }\n")
        file(WRITE "${root}/game/modules/${dependency}/CMakeLists.txt"
            "add_library(symocraft_${dependency} STATIC src/owned.cpp)\nset_target_properties(symocraft_${dependency} PROPERTIES LINKER_LANGUAGE CXX)\n")
        string(APPEND cmakelists "add_subdirectory(game/modules/${dependency})\n")
        string(APPEND module_cmake "target_link_libraries(symocraft_${module} PRIVATE symocraft_${dependency})\n")
        set(expected "Boundary violation: target")
    elseif(case STREQUAL "target-module-app")
        file(WRITE "${root}/game/app/CMakeLists.txt" "add_library(symocraft_startup INTERFACE)\n")
        string(APPEND cmakelists "add_subdirectory(game/app)\n")
        string(APPEND module_cmake "target_link_libraries(symocraft_world PRIVATE symocraft_startup)\n")
        set(expected "Boundary violation: module")
    elseif(case STREQUAL "target-production-test")
        file(WRITE "${root}/test/CMakeLists.txt" "add_library(test_fixture INTERFACE)\n")
        string(APPEND cmakelists "add_subdirectory(test)\n")
        string(APPEND module_cmake "target_link_libraries(symocraft_world PRIVATE test_fixture)\n")
        set(expected "Boundary violation: production")
    elseif(case STREQUAL "broad-include")
        string(APPEND module_cmake "target_include_directories(symocraft_world PUBLIC \"${root}/vendor\")\n")
        set(expected "Boundary violation: symocraft_world exposes broad")
    elseif(case STREQUAL "duplicate-source")
        string(APPEND module_cmake "add_library(duplicate STATIC src/owned.cpp)\nset_target_properties(duplicate PROPERTIES LINKER_LANGUAGE CXX)\n")
        set(expected "Boundary violation: duplicate production source")
    elseif(case STREQUAL "public-private-path")
        string(APPEND module_cmake "target_include_directories(symocraft_world PUBLIC \"${root}/game/modules/world/src\")\n")
        set(expected "Boundary violation: symocraft_world publishes private implementation")
    elseif(case STREQUAL "test-include")
        string(APPEND module_cmake "target_include_directories(symocraft_world PRIVATE \"${root}/test/support\")\n")
        set(expected "Boundary violation: production symocraft_world gains test include")
    elseif(case STREQUAL "target-game-benchmark")
        file(MAKE_DIRECTORY "${root}/tools/benchmark")
        file(WRITE "${root}/tools/benchmark/CMakeLists.txt" "add_library(benchmark_core INTERFACE)\n")
        file(WRITE "${root}/game/app/CMakeLists.txt" "add_library(symocraft_startup INTERFACE)\ntarget_link_libraries(symocraft_startup INTERFACE benchmark_core)\n")
        string(APPEND cmakelists "add_subdirectory(tools/benchmark)\nadd_subdirectory(game/app)\n")
        set(expected "Boundary violation: game symocraft_startup -> independent benchmark")
    else()
        string(APPEND module_cmake "target_link_libraries(symocraft_world PRIVATE symocraft_world)\n")
        set(expected "Boundary violation: cyclic production")
    endif()
    file(WRITE "${root}/game/modules/${module}/CMakeLists.txt" "${module_cmake}")
    string(APPEND cmakelists "add_subdirectory(game/modules/${module})\ninclude(\"${REPO}/cmake/ModuleBoundaries.cmake\")\nsymocraft_validate_boundaries()\n")
    file(WRITE "${root}/CMakeLists.txt" "${cmakelists}")
    execute_process(COMMAND "${CMAKE_COMMAND}" -S "${root}" -B "${root}/build" -G Ninja "-DCMAKE_MAKE_PROGRAM=${NINJA}"
        RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
    file(WRITE "${root}/result.log" "${output}${error}")
    if(result EQUAL 0 OR NOT error MATCHES "${expected}")
        message(FATAL_ERROR "Negative target case ${case} failed for the wrong reason: ${output}${error}")
    endif()
    message(STATUS "Rejected ${case} during real CMake configuration")
endforeach()
