cmake_minimum_required(VERSION 3.22)
foreach(argument IN ITEMS REPO OUTPUT NINJA)
    if(NOT DEFINED ${argument})
        message(FATAL_ERROR "Pass REPO, OUTPUT and NINJA absolute paths from an x64 MSVC developer environment.")
    endif()
endforeach()
if(NOT DEFINED CONFIGURATION)
    set(CONFIGURATION Release)
endif()
if(NOT CONFIGURATION MATCHES "^(Debug|Release)$")
    message(FATAL_ERROR "CONFIGURATION must be Debug or Release.")
endif()
file(MAKE_DIRECTORY "${OUTPUT}")
foreach(mode IN ITEMS no-tests cpu-only standalone-runner root-runner-only game-only)
    set(source "${REPO}")
    set(options "-DCMAKE_MAKE_PROGRAM=${NINJA}" "-DCMAKE_BUILD_TYPE=${CONFIGURATION}"
        "-DCMAKE_INSTALL_PREFIX=${OUTPUT}/install/${mode}")
    set(has_game OFF)
    if(mode STREQUAL "no-tests")
        list(APPEND options -DBUILD_TESTING=OFF)
        set(has_game ON)
    elseif(mode STREQUAL "cpu-only")
        list(APPEND options -DBUILD_TESTING=ON -DSYMOCRAFT_CPU_ONLY=ON)
    elseif(mode STREQUAL "standalone-runner")
        set(source "${REPO}/tools/benchmark")
        list(APPEND options -DBUILD_TESTING=ON)
    elseif(mode STREQUAL "game-only")
        list(APPEND options -DBUILD_TESTING=ON -DSYMOCRAFT_BUILD_GAME=ON -DSYMOCRAFT_BUILD_BENCHMARK=OFF)
        set(has_game ON)
    else()
        list(APPEND options -DBUILD_TESTING=OFF -DSYMOCRAFT_BUILD_GAME=OFF -DSYMOCRAFT_BUILD_CPU_MODULES=OFF -DSYMOCRAFT_BUILD_BENCHMARK=ON)
    endif()
    foreach(step IN ITEMS configure build install)
        if(step STREQUAL "configure")
            set(command "${CMAKE_COMMAND}" -S "${source}" -B "${OUTPUT}/${mode}" -G Ninja ${options})
        elseif(step STREQUAL "build")
            set(command "${CMAKE_COMMAND}" --build "${OUTPUT}/${mode}" --parallel 8)
        else()
            set(command "${CMAKE_COMMAND}" --install "${OUTPUT}/${mode}")
        endif()
        execute_process(COMMAND ${command} RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
        file(WRITE "${OUTPUT}/${mode}-${step}.log" "${output}${error}")
        if(NOT result EQUAL 0)
            message(FATAL_ERROR "${mode} ${step} failed: inspect ${OUTPUT}/${mode}-${step}.log\n${output}${error}")
        endif()
        message(STATUS "${mode} ${step}: passed")
    endforeach()
    file(READ "${OUTPUT}/${mode}/build.ninja" graph)
    file(READ "${OUTPUT}/${mode}/CMakeFiles/TargetDirectories.txt" targets)
    file(STRINGS "${OUTPUT}/${mode}/CMakeCache.txt" graphics_cache
        REGEX "^(SDL[^:]*|GLFW[^:]*|glfw[^:]*):")
    set(target_graph "${graph}\n${targets}")
    string(TOLOWER "${target_graph}" target_graph_lower)
    if(target_graph_lower MATCHES "glfw[^ /\n]*\\.dir|vendor/glfw/")
        message(FATAL_ERROR "Retired GLFW targets configured in ${mode}")
    endif()
    file(STRINGS "${OUTPUT}/${mode}/CMakeCache.txt" glfw_cache REGEX "^([Gg][Ll][Ff][Ww])[^:]*:")
    if(glfw_cache)
        message(FATAL_ERROR "Retired GLFW options configured in ${mode}: ${glfw_cache}")
    endif()
    if(mode STREQUAL "no-tests")
        if(target_graph MATCHES "(fixture|_tests|header_foundation).*\\.dir")
            message(FATAL_ERROR "BUILD_TESTING=OFF created test/support targets")
        endif()
    endif()
    if(NOT has_game)
        if(target_graph MATCHES "symocraft_(platform|renderer|glad)\\.dir|SymoCraft\\.dir|glfw\\.dir|SDL[^ /\n]*\\.dir|vendor/(sdl3|glfw)/")
            message(FATAL_ERROR "Independent ${mode} mode configured game/graphics targets")
        endif()
        if(graphics_cache)
            message(FATAL_ERROR "Independent ${mode} mode configured window dependency options: ${graphics_cache}")
        endif()
    else()
        if(NOT target_graph MATCHES "SDL3-static\\.dir")
            message(FATAL_ERROR "Game mode ${mode} did not configure the SDL static target")
        endif()
        foreach(option IN ITEMS SDL_STATIC SDL_SHARED SDL_TEST_LIBRARY SDL_TESTS SDL_EXAMPLES SDL_INSTALL)
            if(option STREQUAL "SDL_STATIC")
                set(expected ON)
            else()
                set(expected OFF)
            endif()
            file(STRINGS "${OUTPUT}/${mode}/CMakeCache.txt" entry REGEX "^${option}:[^=]+=${expected}$")
            if(NOT entry)
                message(FATAL_ERROR "Game mode ${mode} must explicitly configure ${option}=${expected}")
            endif()
        endforeach()
        if(target_graph MATCHES "SDL3-shared\\.dir|SDL3_test\\.dir")
            message(FATAL_ERROR "Game mode ${mode} configured shared SDL or SDL test targets")
        endif()
        file(GLOB_RECURSE static_libraries "${OUTPUT}/${mode}/SDL3-static*.lib")
        if(NOT static_libraries)
            message(FATAL_ERROR "Game mode ${mode} did not build the SDL static library")
        endif()
    endif()
    if(mode STREQUAL "standalone-runner" OR mode STREQUAL "root-runner-only")
        if(target_graph MATCHES "symocraft_(foundation|world|platform|renderer|glad)\\.dir|SymoCraft\\.dir|glfw\\.dir")
            message(FATAL_ERROR "Independent runner mode ${mode} created game/graphics targets")
        endif()
    elseif(mode STREQUAL "game-only" OR mode STREQUAL "cpu-only")
        if(target_graph MATCHES "benchmark_core\\.dir|SymoCraftBenchmark\\.dir" OR EXISTS "${OUTPUT}/${mode}/bin/SymoCraftBenchmark.exe")
            message(FATAL_ERROR "${mode} created the benchmark runner")
        endif()
    endif()
    file(GLOB_RECURSE build_artifacts RELATIVE "${OUTPUT}/${mode}"
        "${OUTPUT}/${mode}/*.lib" "${OUTPUT}/${mode}/*.dll" "${OUTPUT}/${mode}/*.obj")
    foreach(path IN LISTS build_artifacts)
        string(TOLOWER "${path}" lower_path)
        if(lower_path MATCHES "(^|/)glfw[^/]*\\.(lib|dll|obj)$|cmakefiles/glfw[^/]*\\.dir/|vendor/glfw/")
            message(FATAL_ERROR "Retired GLFW artifact built in ${mode}: ${path}")
        endif()
        if(lower_path MATCHES "(^|/)sdl3[^/]*\\.dll$")
            message(FATAL_ERROR "Shared SDL artifact built in ${mode}: ${path}")
        endif()
        if(NOT has_game AND lower_path MATCHES "(^|/)(sdl[^/]*|glfw[^/]*|symocraft_glad[^/]*)\\.(lib|dll)$|cmakefiles/(sdl[^/]*|glfw|symocraft_glad)\\.dir/")
            message(FATAL_ERROR "Independent ${mode} mode built a window/GL artifact: ${path}")
        endif()
    endforeach()
    file(GLOB_RECURSE installed RELATIVE "${OUTPUT}/install/${mode}" "${OUTPUT}/install/${mode}/*")
    foreach(path IN LISTS installed)
        if(path MATCHES "(fixture|_tests|header_).*\\.exe$|\\.(lib|pdb|obj)$")
            message(FATAL_ERROR "Test/development artifact leaked into ${mode} installation: ${path}")
        endif()
        string(TOLOWER "${path}" lower_path)
        if(lower_path MATCHES "(^|/)[^/]*glfw[^/]*($|/)")
            message(FATAL_ERROR "Retired GLFW material leaked into ${mode} installation: ${path}")
        endif()
        if(lower_path MATCHES "(^|/)sdl3[^/]*\\.dll$")
            message(FATAL_ERROR "Shared SDL leaked into ${mode} installation: ${path}")
        endif()
        if(NOT has_game AND lower_path MATCHES "(^|/)licenses/[^/]*sdl[^/]*")
            message(FATAL_ERROR "SDL license leaked into independent ${mode} installation: ${path}")
        endif()
    endforeach()
    if(has_game)
        set(license "${OUTPUT}/install/${mode}/licenses/SDL3-LICENSE.txt")
        if(NOT EXISTS "${license}")
            message(FATAL_ERROR "Game mode ${mode} did not install the SDL license")
        endif()
        file(SHA256 "${REPO}/vendor/sdl3/LICENSE.txt" source_license_hash)
        file(SHA256 "${license}" installed_license_hash)
        if(NOT source_license_hash STREQUAL installed_license_hash)
            message(FATAL_ERROR "Game mode ${mode} installed a different SDL license")
        endif()
    endif()
    file(WRITE "${OUTPUT}/${mode}-install-files.txt" "${installed}\n")
endforeach()
message(STATUS "${CONFIGURATION} build/install target matrix passed; run CPU-only and standalone-runner CTest separately.")
