# Run in an x64 MSVC developer environment with VSLANG=1033.
cmake_minimum_required(VERSION 3.22)
if(NOT DEFINED REPO OR NOT DEFINED OUTPUT OR NOT DEFINED NINJA)
    message(FATAL_ERROR "Pass REPO, OUTPUT and NINJA absolute paths.")
endif()
if(NOT DEFINED CONFIGURATION)
    set(CONFIGURATION Release)
endif()
if(NOT CONFIGURATION MATCHES "^(Debug|Release)$")
    message(FATAL_ERROR "CONFIGURATION must be Debug or Release.")
endif()
foreach(mode IN ITEMS runner-only game-only standalone-runner cpu-only)
    set(source "${REPO}")
    set(options -DBUILD_TESTING=OFF "-DCMAKE_BUILD_TYPE=${CONFIGURATION}" "-DCMAKE_MAKE_PROGRAM=${NINJA}")
    if(mode STREQUAL "runner-only")
        list(APPEND options -DSYMOCRAFT_BUILD_GAME=OFF -DSYMOCRAFT_BUILD_CPU_MODULES=OFF -DSYMOCRAFT_BUILD_BENCHMARK=ON)
    elseif(mode STREQUAL "game-only")
        list(APPEND options -DSYMOCRAFT_BUILD_GAME=ON -DSYMOCRAFT_BUILD_BENCHMARK=OFF)
    elseif(mode STREQUAL "cpu-only")
        list(APPEND options -DSYMOCRAFT_CPU_ONLY=ON)
    else()
        set(source "${REPO}/tools/benchmark")
    endif()
    execute_process(COMMAND "${CMAKE_COMMAND}" -S "${source}" -B "${OUTPUT}/${mode}" -G Ninja ${options}
        COMMAND_ERROR_IS_FATAL ANY)
    execute_process(COMMAND "${CMAKE_COMMAND}" --build "${OUTPUT}/${mode}" --parallel 8 COMMAND_ERROR_IS_FATAL ANY)
    file(READ "${OUTPUT}/${mode}/build.ninja" graph)
    file(READ "${OUTPUT}/${mode}/CMakeFiles/TargetDirectories.txt" targets)
    file(STRINGS "${OUTPUT}/${mode}/CMakeCache.txt" graphics_cache
        REGEX "^(SDL[^:]*|GLFW[^:]*|glfw[^:]*):")
    set(target_graph "${graph}\n${targets}")
    string(TOLOWER "${target_graph}" target_graph_lower)
    if(target_graph_lower MATCHES "glfw[^ /\n]*\\.dir|vendor/glfw/")
        message(FATAL_ERROR "Retired GLFW targets configured in ${mode}.")
    endif()
    file(STRINGS "${OUTPUT}/${mode}/CMakeCache.txt" glfw_cache REGEX "^([Gg][Ll][Ff][Ww])[^:]*:")
    if(glfw_cache)
        message(FATAL_ERROR "Retired GLFW options configured in ${mode}: ${glfw_cache}")
    endif()
    if(mode STREQUAL "game-only")
        if(target_graph MATCHES "benchmark_core\\.dir|SymoCraftBenchmark\\.dir" OR EXISTS "${OUTPUT}/${mode}/bin/SymoCraftBenchmark.exe")
            message(FATAL_ERROR "Game-only build leaked the runner.")
        endif()
        if(NOT target_graph MATCHES "SDL3-static\\.dir" OR target_graph MATCHES "SDL3-shared\\.dir|SDL3_test\\.dir")
            message(FATAL_ERROR "Game-only build must configure only the SDL static dependency.")
        endif()
        foreach(option IN ITEMS SDL_STATIC SDL_SHARED SDL_TEST_LIBRARY SDL_TESTS SDL_EXAMPLES SDL_INSTALL)
            if(option STREQUAL "SDL_STATIC")
                set(expected ON)
            else()
                set(expected OFF)
            endif()
            file(STRINGS "${OUTPUT}/${mode}/CMakeCache.txt" entry REGEX "^${option}:[^=]+=${expected}$")
            if(NOT entry)
                message(FATAL_ERROR "Game-only build must explicitly configure ${option}=${expected}.")
            endif()
        endforeach()
        file(GLOB_RECURSE static_libraries "${OUTPUT}/${mode}/SDL3-static*.lib")
        if(NOT static_libraries)
            message(FATAL_ERROR "Game-only build did not build the SDL static library.")
        endif()
    else()
        if(target_graph MATCHES "symocraft_(platform|renderer|glad)\\.dir|SymoCraft\\.dir|glfw\\.dir|SDL[^ /\n]*\\.dir|vendor/(sdl3|glfw)/" OR EXISTS "${OUTPUT}/${mode}/bin/SymoCraft.exe")
            message(FATAL_ERROR "Runner-only build leaked game/GL dependencies.")
        endif()
        if(graphics_cache)
            message(FATAL_ERROR "Independent ${mode} mode configured window dependencies: ${graphics_cache}")
        endif()
        if(NOT mode STREQUAL "cpu-only" AND target_graph MATCHES "symocraft_(foundation|world)\\.dir")
            message(FATAL_ERROR "Runner-only build leaked CPU game modules.")
        endif()
        if(mode STREQUAL "cpu-only" AND target_graph MATCHES "benchmark_core\\.dir|SymoCraftBenchmark\\.dir")
            message(FATAL_ERROR "CPU-only build leaked the runner.")
        endif()
    endif()
    file(GLOB_RECURSE artifacts RELATIVE "${OUTPUT}/${mode}"
        "${OUTPUT}/${mode}/*.lib" "${OUTPUT}/${mode}/*.dll" "${OUTPUT}/${mode}/*.obj")
    foreach(path IN LISTS artifacts)
        string(TOLOWER "${path}" lower_path)
        if(lower_path MATCHES "(^|/)glfw[^/]*\\.(lib|dll|obj)$|cmakefiles/glfw[^/]*\\.dir/|vendor/glfw/")
            message(FATAL_ERROR "Retired GLFW artifact built in ${mode}: ${path}")
        endif()
        if(lower_path MATCHES "(^|/)sdl3[^/]*\\.dll$")
            message(FATAL_ERROR "Shared SDL artifact built in ${mode}: ${path}")
        endif()
        if(NOT mode STREQUAL "game-only" AND lower_path MATCHES "(^|/)(sdl[^/]*|glfw[^/]*|symocraft_glad[^/]*)\\.(lib|dll)$|cmakefiles/(sdl[^/]*|glfw|symocraft_glad)\\.dir/")
            message(FATAL_ERROR "Independent ${mode} mode built a window/GL artifact: ${path}")
        endif()
    endforeach()
    if(target_graph MATCHES "(fixture|_tests|header_foundation).*\\.dir")
        message(FATAL_ERROR "BUILD_TESTING=OFF created test/support targets in ${mode}.")
    endif()
    message(STATUS "${mode}: ${CONFIGURATION} build and dependency boundary passed")
endforeach()
