cmake_minimum_required(VERSION 3.22)
foreach(argument IN ITEMS REPO OUTPUT NINJA)
    if(NOT DEFINED ${argument})
        message(FATAL_ERROR "Pass REPO, OUTPUT and NINJA absolute paths from an x64 MSVC developer environment.")
    endif()
endforeach()
file(MAKE_DIRECTORY "${OUTPUT}")
foreach(mode IN ITEMS no-tests standalone-runner root-runner-only)
    set(source "${REPO}")
    set(options "-DCMAKE_MAKE_PROGRAM=${NINJA}" -DCMAKE_BUILD_TYPE=Release
        "-DCMAKE_INSTALL_PREFIX=${OUTPUT}/install/${mode}")
    if(mode STREQUAL "no-tests")
        list(APPEND options -DBUILD_TESTING=OFF)
    elseif(mode STREQUAL "standalone-runner")
        set(source "${REPO}/tools/benchmark")
        list(APPEND options -DBUILD_TESTING=ON)
    else()
        list(APPEND options -DBUILD_TESTING=OFF -DSYMOCRAFT_BUILD_GAME=OFF -DSYMOCRAFT_BUILD_CPU_MODULES=OFF -DSYMOCRAFT_BUILD_BENCHMARK=ON)
    endif()
    foreach(step IN ITEMS configure build install)
        if(step STREQUAL "configure")
            set(command "${CMAKE_COMMAND}" -S "${source}" -B "${OUTPUT}/${mode}" -G Ninja ${options})
        elseif(step STREQUAL "build")
            set(command "${CMAKE_COMMAND}" --build "${OUTPUT}/${mode}" --parallel 8)
        else()
            set(command "${CMAKE_COMMAND}" --install "${OUTPUT}/${mode}")
        endif()
        execute_process(COMMAND ${command} RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
        file(WRITE "${OUTPUT}/${mode}-${step}.log" "${output}${error}")
        if(NOT result EQUAL 0)
            message(FATAL_ERROR "${mode} ${step} failed: inspect ${OUTPUT}/${mode}-${step}.log\n${output}${error}")
        endif()
        message(STATUS "${mode} ${step}: passed")
    endforeach()
    file(READ "${OUTPUT}/${mode}/build.ninja" graph)
    if(mode STREQUAL "no-tests")
        if(graph MATCHES "(fixture|_tests|header_foundation).*\\.dir")
            message(FATAL_ERROR "BUILD_TESTING=OFF created test/support targets")
        endif()
    else()
        if(graph MATCHES "symocraft_(foundation|world|platform|renderer|glad)\\.dir|SymoCraft\\.dir|glfw\\.dir")
            message(FATAL_ERROR "Independent runner mode ${mode} created game/graphics targets")
        endif()
    endif()
    file(GLOB_RECURSE installed RELATIVE "${OUTPUT}/install/${mode}" "${OUTPUT}/install/${mode}/*")
    foreach(path IN LISTS installed)
        if(path MATCHES "(fixture|_tests|header_).*\\.exe$|\\.(lib|pdb|obj)$")
            message(FATAL_ERROR "Test/development artifact leaked into ${mode} installation: ${path}")
        endif()
    endforeach()
    file(WRITE "${OUTPUT}/${mode}-install-files.txt" "${installed}\n")
endforeach()
message(STATUS "Build/install target matrix passed; run standalone-runner CTest separately.")
